/**
 * Configuration loader for API connectivity
 * Automatically detects environment and loads appropriate API base URL
 */

import { Platform } from 'react-native';

// Try to load from config file (generated by startup scripts)
let CONFIG = null;

try {
  const configFile = require('../.api-config.json');
  CONFIG = configFile;
} catch (e) {
  // Config file not generated yet, will use defaults
  CONFIG = null;
}

// Determine API base URL based on platform and environment
const getApiBaseUrl = () => {
  // If config was generated by startup script, use it
  if (CONFIG && CONFIG.api_base_url) {
    return CONFIG.api_base_url;
  }

  // Platform-specific defaults
  if (Platform.OS === 'android') {
    // Android emulator
    return 'http://10.0.2.2:8000/api';
  }
  
  if (Platform.OS === 'ios') {
    // iOS simulator
    return 'http://localhost:8000/api';
  }

  if (Platform.OS === 'web') {
    // Web - detect dynamically
    const host = typeof window !== 'undefined' ? window.location.hostname : 'localhost';
    return `http://${host}:8000/api`;
  }

  // Default fallback
  return 'http://localhost:8000/api';
};

const config = {
  api_base_url: getApiBaseUrl(),
  backend_url: (CONFIG?.backend_url || getApiBaseUrl().replace('/api', '')),
  api_port: CONFIG?.api_port || 8000,
  frontend_port: CONFIG?.frontend_port || 8081,
  environment: CONFIG?.environment || 'development',
};

export default config;
